### ISSUE TITLE
建议增加多种分辨率支持

### ISSUE THREAD

**Issue by lordshenone** [jiangKerman/VegaConflictBot#1]
正好租了个vps，就想着在vps里跑游戏和脚本，结果游戏可以正常运行。但是脚本没法用。看了一下是分辨率达不到脚本的要求。但vps也没法改分辨率。系统是windows sever 2012。希望有空能改进一下啦，谢谢。

**Comment by jiangKerman** [comment]
远程桌面无法达到预期效果，是因为pyautogui库自生的原因，这类完全模拟键鼠的三方库都不能用远程桌面。

如果你只是实现后台挂机，请考虑使用虚拟机比如virtualbox+脚本挂机，这是我目前自己在用的方案。

请持续关注该项目，近期在针对虚拟机（之类的土豆服务器）挂机进行优化，新版本将很快发布。

开发日志不定期更新 https://jiangkerman.cc/2022/08/29/%E5%86%99%E4%B8%80%E4%B8%AAVEGA-Conflict%E6%89%93%E6%80%AA%E8%84%9A%E6%9C%AC%E6%9D%A5%E8%A7%A3%E6%94%BE%E5%8F%8C%E6%89%8B/
