### ISSUE TITLE
能不能用版本低点的python打包exe文件，你这个版本windows7没法跑。

### ISSUE THREAD

**Issue by lordshenone** [jiangKerman/VegaConflictBot#2]
能不能用版本低点的python打包exe文件，你这个版本windows7没法跑。查了一下是因为python3.10开始不支持windows7了。这个好头大，虚拟机里游戏啥的都装好了，结果python运行不起来😒

**Comment by jiangKerman** [comment]
我没有考虑过win7系统。

你可以尝试自己从源码构建，低版本python也能跑。

**Comment by lordshenone** [comment]
最新版好像看不到源码，能否放出来，谢谢。-------- 原始邮件 --------发件人： jiangKerman ***@***.***>日期： 2022年11月20日周日 22:12收件人： jiangKerman/VegaConflictBot ***@***.***>抄送： lordshenone ***@***.***>, Author ***@***.***>主    题： Re: [jiangKerman/VegaConflictBot] 能不能用版本低点的python打包exe文件，你这个版本windows7没法跑。 (Issue #2)

我没有考虑过win7系统。

你可以尝试自己从源码构建，低版本python也能跑。

**Comment by jiangKerman** [comment]
源码已更新，请摸索着自行构建。
现在还没有把相关依赖加进去，后续会完善。

**Comment by lordshenone** [comment]
好的，多谢-------- 原始邮件 --------发件人： jiangKerman ***@***.***>日期： 2022年11月22日周二 11:11收件人： jiangKerman/VegaConflictBot ***@***.***>抄送： lordshenone ***@***.***>, Author ***@***.***>主    题： Re: [jiangKerman/VegaConflictBot] 能不能用版本低点的python打包exe文件，你这个版本windows7没法跑。 (Issue #2)

源码已更新，请摸索着自行构建。

现在还没有把相关依赖加进去，后续会完善。
